# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
      
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install
        
      - name: Build gatsby
        run: npm run build
      
      - name: public to docs folder
        run: |
          rm -dr docs
          mv -f public docs
    
      - name: commit and push
        run: |
          git config user.name "MiniHack"
          git config user.email "MiniHack@onlineminihack.github.io"
          
          git add .
          git commit -m "Publish"
          git push
          

          
        
        
        
        
